FROM python:latest

RUN mkdir -p /app/CSMS/ocpp_server
RUN mkdir -p /app/Exceptions
RUN mkdir -p /app/rabbit_mp

WORKDIR /app

COPY ./CSMS/ocpp_server /app/CSMS/ocpp_server
COPY ./rabbit_mq /app/rabbit_mq
COPY ./Exceptions /app/Exceptions

RUN pip install -r CSMS/ocpp_server/requirements.txt

CMD ["python3", "-m", "CSMS.ocpp_server.ocpp_server", "-rb", "amqp://guest:guest@rabbitmq/"]