FROM python:latest

RUN mkdir -p /app/CSMS/db
RUN mkdir -p /app/rabbit_mp

WORKDIR /app

COPY ./CSMS/db /app/CSMS/db
COPY ./rabbit_mq /app/rabbit_mq

RUN pip install -r CSMS/db/requirements.txt

CMD ["python3", "-m", "CSMS.db.db", "-rb", "amqp://guest:guest@rabbitmq/", "-db", "mysql"]
