FROM python:latest

RUN mkdir -p /app/CSMS/api
RUN mkdir -p /app/rabbit_mp

WORKDIR /app

COPY ./CSMS/api /app/CSMS/api
COPY ./.env /.env
COPY ./rabbit_mq /app/rabbit_mq

RUN pip install -r CSMS/api/requirements.txt

CMD ["python3", "-m", "CSMS.api.api", "-rb", "amqp://guest:guest@rabbitmq/"]