FROM python:latest

RUN mkdir -p /app/CSMS/api
RUN mkdir -p /app/Exceptions
RUN mkdir -p /app/rabbit_mp

WORKDIR /app

COPY ./CSMS/api /app/CSMS/api
COPY ./rabbit_mq /app/rabbit_mq
COPY ./Exceptions /app/Exceptions

RUN pip install -r CSMS/api/requirements.txt

CMD ["python3", "-m", "CSMS.api.api", "-rb", "amqp://guest:guest@rabbitmq/"]